apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rpe-kainos-team-talks App
name: rpe-kainos-team-talks
home: https://github.com/hmcts/rpe-kainos-team-talks
version: 0.0.1
maintainers:
  - name: HMCTS rpe team
dependencies:
  - name: java
    version: 3.0.2
    repository: '@hmctspublic'
